export interface Product {
  id: string
  name: string
  price: number
  franchise: string
  category: "Figurines" | "Display" | "Booster" | "Blister" | "Autres"
  type: string
  manufacturer: string
  character: string
  rarity?: string
  scale?: string
  availability: "En Stock" | "Precommande" | "Stock Limite"
  badge?: string
  badgeColor?: "pink" | "yellow"
  image: string
  rating: number
  reviewCount: number
  popularity: number
  dateAdded: string
}


export const allProducts: Product[] = [
  {
    id: "fig-gojo-01",
    name: "Figurine Gojo Satoru Domaine Infini",
    price: 89.99,
    franchise: "Jujutsu Kaisen",
    category: "Figurines",
    type: "Figurine Premium",
    manufacturer: "Good Smile Company",
    character: "Satoru Gojo",
    scale: "1/7",
    availability: "En Stock",
    badge: "BEST SELLER",
    badgeColor: "pink",
    image: "/products/figurine-gojo.jpg",
    rating: 4.8,
    reviewCount: 127,
    popularity: 98,
    dateAdded: "2025-11-15",
  },
  {
    id: "fig-luffy-01",
    name: "Figurine Luffy Gear 5 S.H.Figuarts",
    price: 149.99,
    franchise: "One Piece",
    category: "Figurines",
    type: "Figurine Premium",
    manufacturer: "Bandai",
    character: "Monkey D. Luffy",
    scale: "1/8",
    availability: "En Stock",
    badge: "NOUVEAU",
    badgeColor: "pink",
    image: "/products/figurine-luffy.jpg",
    rating: 4.9,
    reviewCount: 89,
    popularity: 95,
    dateAdded: "2026-01-20",
  },
  {
    id: "card-pokemon-01",
    name: "Booster Box Pokemon Ecarlate et Violet",
    price: 189.99,
    franchise: "Pokemon",
    category: "Booster",
    type: "Booster Box",
    manufacturer: "The Pokemon Company",
    character: "Divers",
    rarity: "Ultra Rare",
    availability: "En Stock",
    badge: "BEST SELLER",
    badgeColor: "pink",
    image: "/products/booster-pokemon.jpg",
    rating: 4.7,
    reviewCount: 203,
    popularity: 97,
    dateAdded: "2025-10-05",
  },
  {
    id: "fig-naruto-01",
    name: "Statuette Naruto Uzumaki Baryon Mode",
    price: 199.99,
    franchise: "Naruto",
    category: "Figurines",
    type: "Figurine Premium",
    manufacturer: "Tsume Art",
    character: "Naruto Uzumaki",
    scale: "1/6",
    availability: "Stock Limite",
    badge: "EDITION LIMITEE",
    badgeColor: "yellow",
    image: "/products/figurine-naruto.jpg",
    rating: 4.9,
    reviewCount: 56,
    popularity: 90,
    dateAdded: "2025-12-01",
  },
  {
    id: "card-yugioh-01",
    name: "Carte Ultra Rare Dragon Blanc aux Yeux Bleus",
    price: 34.99,
    franchise: "Yu-Gi-Oh!",
    category: "Autres",
    type: "Carte a l'unite",
    manufacturer: "Konami",
    character: "Dragon Blanc",
    rarity: "Ultra Rare",
    availability: "En Stock",
    image: "/products/card-yugioh.jpg",
    rating: 4.6,
    reviewCount: 78,
    popularity: 82,
    dateAdded: "2025-09-10",
  },
  {
    id: "fig-tanjiro-01",
    name: "Nendoroid Tanjiro Kamado",
    price: 54.99,
    franchise: "Demon Slayer",
    category: "Figurines",
    type: "Figurine Premium",
    manufacturer: "Good Smile Company",
    character: "Tanjiro Kamado",
    scale: "Non-scale",
    availability: "En Stock",
    badge: "NOUVEAU",
    badgeColor: "pink",
    image: "/products/figurine-tanjiro.jpg",
    rating: 4.8,
    reviewCount: 112,
    popularity: 88,
    dateAdded: "2026-01-05",
  },
  {
    id: "card-op-01",
    name: "Booster Box One Piece OP-09",
    price: 124.99,
    franchise: "One Piece",
    category: "Booster",
    type: "Booster Box",
    manufacturer: "Bandai",
    character: "Divers",
    rarity: "Secret Rare",
    availability: "Precommande",
    badge: "PRECOMMANDE",
    badgeColor: "yellow",
    image: "/products/booster-onepiece.jpg",
    rating: 4.5,
    reviewCount: 34,
    popularity: 85,
    dateAdded: "2026-02-01",
  },
  {
    id: "fig-goku-01",
    name: "Figurine Goku Ultra Instinct",
    price: 79.99,
    franchise: "Dragon Ball",
    category: "Figurines",
    type: "Figurine Premium",
    manufacturer: "Bandai",
    character: "Son Goku",
    scale: "1/8",
    availability: "En Stock",
    badge: "BEST SELLER",
    badgeColor: "pink",
    image: "/products/figurine-goku.jpg",
    rating: 4.7,
    reviewCount: 156,
    popularity: 93,
    dateAdded: "2025-08-20",
  },
  {
    id: "acc-protege-01",
    name: "Protege-cartes Premium Dragon Ball x60",
    price: 9.99,
    franchise: "Dragon Ball",
    category: "Autres",
    type: "Protege-cartes",
    manufacturer: "Ultra Pro",
    character: "Divers",
    availability: "En Stock",
    image: "/products/accessoire-protege.jpg",
    rating: 4.3,
    reviewCount: 45,
    popularity: 70,
    dateAdded: "2025-11-01",
  },
  {
    id: "fig-deku-01",
    name: "Figurine Deku Full Cowling Pop Up Parade",
    price: 39.99,
    franchise: "My Hero Academia",
    category: "Figurines",
    type: "Figurine Premium",
    manufacturer: "Good Smile Company",
    character: "Izuku Midoriya",
    scale: "Non-scale",
    availability: "En Stock",
    badge: "NOUVEAU",
    badgeColor: "pink",
    image: "/products/figurine-deku.jpg",
    rating: 4.6,
    reviewCount: 67,
    popularity: 80,
    dateAdded: "2026-01-10",
  },
  {
    id: "card-pokemon-02",
    name: "Carte Ultra Rare Charizard VMAX",
    price: 29.99,
    franchise: "Pokemon",
    category: "Display",
    type: "Carte a l'unite",
    manufacturer: "The Pokemon Company",
    character: "Charizard",
    rarity: "Ultra Rare",
    availability: "Stock Limite",
    badge: "STOCK LIMITE",
    badgeColor: "yellow",
    image: "/products/card-pokemon-rare.jpg",
    rating: 4.9,
    reviewCount: 189,
    popularity: 96,
    dateAdded: "2025-07-15",
  },
  {
    id: "fig-zoro-01",
    name: "Statuette Zoro Enma Tsume Art",
    price: 349.99,
    franchise: "One Piece",
    category: "Figurines",
    type: "Figurine Premium",
    manufacturer: "Tsume Art",
    character: "Roronoa Zoro",
    scale: "1/6",
    availability: "Precommande",
    badge: "PRECOMMANDE",
    badgeColor: "yellow",
    image: "/products/figurine-zoro.jpg",
    rating: 5.0,
    reviewCount: 23,
    popularity: 91,
    dateAdded: "2026-02-05",
  },
  {
    id: "fig-gojo-02",
    name: "Figurine Gojo Satoru Hollow Purple Figma",
    price: 119.99,
    franchise: "Jujutsu Kaisen",
    category: "Figurines",
    type: "Figurine Premium",
    manufacturer: "Good Smile Company",
    character: "Satoru Gojo",
    scale: "1/7",
    availability: "En Stock",
    image: "/products/figurine-gojo.jpg",
    rating: 4.7,
    reviewCount: 78,
    popularity: 87,
    dateAdded: "2025-12-10",
  },
  {
    id: "card-dbscg-01",
    name: "Booster Box Dragon Ball Super Fusion World",
    price: 99.99,
    franchise: "Dragon Ball",
    category: "Booster",
    type: "Booster Box",
    manufacturer: "Bandai",
    character: "Divers",
    rarity: "Super Rare",
    availability: "En Stock",
    badge: "BEST SELLER",
    badgeColor: "pink",
    image: "/products/booster-pokemon.jpg",
    rating: 4.4,
    reviewCount: 91,
    popularity: 84,
    dateAdded: "2025-10-20",
  },
  {
    id: "fig-allmight-01",
    name: "Figurine All Might United States of Smash",
    price: 159.99,
    franchise: "My Hero Academia",
    category: "Figurines",
    type: "Figurine Premium",
    manufacturer: "Banpresto",
    character: "All Might",
    scale: "1/7",
    availability: "En Stock",
    badge: "BEST SELLER",
    badgeColor: "pink",
    image: "/products/figurine-deku.jpg",
    rating: 4.8,
    reviewCount: 104,
    popularity: 89,
    dateAdded: "2025-09-25",
  },
  {
    id: "acc-deckbox-01",
    name: "Deck Box Premium Yu-Gi-Oh! Edition Limitee",
    price: 19.99,
    franchise: "Yu-Gi-Oh!",
    category: "Autres",
    type: "Deck Boxes",
    manufacturer: "Konami",
    character: "Divers",
    availability: "En Stock",
    image: "/products/accessoire-protege.jpg",
    rating: 4.2,
    reviewCount: 33,
    popularity: 65,
    dateAdded: "2025-11-20",
  },
  {
    id: "card-pokemon-03",
    name: "Booster Pack Pokemon Destinees de Paldea",
    price: 5.99,
    franchise: "Pokemon",
    category: "Blister",
    type: "Booster Pack",
    manufacturer: "The Pokemon Company",
    character: "Divers",
    rarity: "Rare",
    availability: "En Stock",
    image: "/products/booster-pokemon.jpg",
    rating: 4.3,
    reviewCount: 267,
    popularity: 92,
    dateAdded: "2025-11-30",
  },
  {
    id: "fig-nezuko-01",
    name: "Nendoroid Nezuko Kamado",
    price: 49.99,
    franchise: "Demon Slayer",
    category: "Figurines",
    type: "Figurine Premium",
    manufacturer: "Good Smile Company",
    character: "Nezuko Kamado",
    scale: "Non-scale",
    availability: "En Stock",
    badge: "BEST SELLER",
    badgeColor: "pink",
    image: "/products/figurine-tanjiro.jpg",
    rating: 4.9,
    reviewCount: 145,
    popularity: 94,
    dateAdded: "2025-08-15",
  },
  {
    id: "acc-playmat-01",
    name: "Tapis de Jeu One Piece Card Game Official",
    price: 24.99,
    franchise: "One Piece",
    category: "Autres",
    type: "Tapis de jeu",
    manufacturer: "Bandai",
    character: "Monkey D. Luffy",
    availability: "En Stock",
    image: "/products/accessoire-protege.jpg",
    rating: 4.5,
    reviewCount: 52,
    popularity: 72,
    dateAdded: "2025-12-15",
  },
  {
    id: "card-yugioh-02",
    name: "Deck de Demarrage Yu-Gi-Oh! 2025",
    price: 12.99,
    franchise: "Yu-Gi-Oh!",
    category: "Autres",
    type: "Decks",
    manufacturer: "Konami",
    character: "Divers",
    rarity: "Commune",
    availability: "En Stock",
    image: "/products/card-yugioh.jpg",
    rating: 4.1,
    reviewCount: 89,
    popularity: 75,
    dateAdded: "2025-10-10",
  },
  {
    id: "fig-eren-01",
    name: "Figurine Eren Yeager Titan Assaillant",
    price: 179.99,
    franchise: "Attack on Titan",
    category: "Figurines",
    type: "Figurine Premium",
    manufacturer: "Banpresto",
    character: "Eren Yeager",
    scale: "1/7",
    availability: "Stock Limite",
    badge: "EDITION LIMITEE",
    badgeColor: "yellow",
    image: "/products/figurine-naruto.jpg",
    rating: 4.8,
    reviewCount: 41,
    popularity: 83,
    dateAdded: "2025-09-01",
  },
  {
    id: "card-magic-01",
    name: "Booster Box Magic Modern Horizons 3",
    price: 249.99,
    franchise: "Magic: The Gathering",
    category: "Booster",
    type: "Booster Box",
    manufacturer: "Wizards of the Coast",
    character: "Divers",
    rarity: "Secret Rare",
    availability: "En Stock",
    image: "/products/booster-pokemon.jpg",
    rating: 4.6,
    reviewCount: 67,
    popularity: 79,
    dateAdded: "2025-11-05",
  },
  {
    id: "fig-vegeta-01",
    name: "Figurine Vegeta Super Saiyan Blue",
    price: 69.99,
    franchise: "Dragon Ball",
    category: "Figurines",
    type: "Figurine Premium",
    manufacturer: "Bandai",
    character: "Vegeta",
    scale: "1/8",
    availability: "En Stock",
    image: "/products/figurine-goku.jpg",
    rating: 4.5,
    reviewCount: 88,
    popularity: 81,
    dateAdded: "2025-10-15",
  },
  {
    id: "acc-classeur-01",
    name: "Classeur Collection Pokemon 9 Pochettes",
    price: 14.99,
    franchise: "Pokemon",
    category: "Autres",
    type: "Classeurs",
    manufacturer: "Ultra Pro",
    character: "Divers",
    availability: "En Stock",
    image: "/products/accessoire-protege.jpg",
    rating: 4.4,
    reviewCount: 76,
    popularity: 74,
    dateAdded: "2025-12-20",
  },
]

export const franchises = [
  "Jujutsu Kaisen",
  "One Piece",
  "Pokemon",
  "Naruto",
  "Yu-Gi-Oh!",
  "Demon Slayer",
  "Dragon Ball",
  "My Hero Academia",
  "Attack on Titan",
  "Magic: The Gathering",
]

export const categories = [
  "Figurines",
  "Display",
  "Booster",
  "Blister",
  "Autres",
]

export const productTypes = [
  "Booster Box",
  "Booster Pack",
  "Decks",
  "Carte a l'unite",
  "Figurine Premium",
  "Protege-cartes",
  "Deck Boxes",
  "Classeurs",
  "Tapis de jeu",
]

export const manufacturers = [
  "Good Smile Company",
  "Bandai",
  "Banpresto",
  "Tsume Art",
  "Konami",
  "The Pokemon Company",
  "Ultra Pro",
  "Wizards of the Coast",
]

export const rarities = [
  "Commune",
  "Rare",
  "Super Rare",
  "Ultra Rare",
  "Secret Rare",
  "Collector",
]

export const scales = [
  "1/6",
  "1/7",
  "1/8",
  "Non-scale",
]

export const availabilities = [
  "En Stock",
  "Precommande",
  "Stock Limite",
]
